module.exports = {
  apps: [
    {
      name: 'restaurantes-worker',
      script: './scripts/worker.mjs',
      args: '--rate=2 --hours=10-19',
      cwd: '/root/pacame/restaurantes-prospect-cr',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '500M',
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 50,
      watch: false,
      env: {
        NODE_ENV: 'production',
        TZ: 'Europe/Madrid',
      },
      error_file: '/root/pacame/restaurantes-prospect-cr/logs/worker-err.log',
      out_file: '/root/pacame/restaurantes-prospect-cr/logs/worker-out.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'restaurantes-webhooks',
      script: './scripts/webhook-server.mjs',
      cwd: '/root/pacame/restaurantes-prospect-cr',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '300M',
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 100,
      watch: false,
      env: {
        NODE_ENV: 'production',
        TZ: 'Europe/Madrid',
        WEBHOOK_PORT: '3030',
      },
      error_file: '/root/pacame/restaurantes-prospect-cr/logs/webhooks-err.log',
      out_file: '/root/pacame/restaurantes-prospect-cr/logs/webhooks-out.log',
      time: true,
      merge_logs: true,
    },
  ],
};
