-- Seed 24 personas iniciales — 3 por cada vertical PACAME.
-- Contenido diseñado con skills: landing-page-generator + copywriting + marketing-psychology
-- Case studies son simulaciones honestas basadas en promedio cliente PACAME (disclaimer visible en UI).

-- Idempotente: on conflict do update
INSERT INTO portfolio_personas (
  vertical_slug, persona_slug, persona_name, persona_tagline, persona_emoji,
  pain_headline, pain_bullets, solution_headline, solution_bullets,
  deliverables, case_study, starting_price_cents, timeline_days, faq,
  hero_image_url, meta_title, meta_description, is_active, sort_order
) VALUES

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: RESTAURANTE
-- ══════════════════════════════════════════════════════════════════════════
('restaurante', 'dueno-restaurante', 'Dueño de Restaurante',
 'Restaurantes con mesa que viven del boca a boca y necesitan digitalizar reservas',
 '🍽️',
 'Cada noche tu restaurante pierde mesas por no tener reserva online',
 '["Clientes llaman a las 22h y tu jefe de sala ya apago telefono","Google muestra tu restaurante pero mandamos al cliente a llamar (50% se pierden)","Los sabados el movil suena sin parar y no podeis atender cocina","No sabes cuantos clientes rebotaron por no poder reservar","Tu carta en PDF pesa 8MB y nadie la abre en mobile"]'::jsonb,
 'Web + reservas online que trabaja mientras duermes',
 '["Tu web con reservas online 24/7 integradas con TheFork/CoverManager","Carta digital QR + multi-idioma (ES/EN/FR)","Google Business Profile conectado — reservan desde Google Maps","Notificaciones email+WhatsApp al confirmar","Panel control donde ves ocupacion en tiempo real"]'::jsonb,
 '["Diseño web responsive premium (Desktop + Mobile + Tablet)","Sistema reservas online integrado + calendario","Carta digital con QR dinamico + fotos HD","Google Business Profile optimizado + integracion reservas","Blog SEO inicial con 5 articulos (nuevos platos, eventos)","Panel admin (editas horarios, menu, eventos sin tocar codigo)","Integraciones email + WhatsApp Business","Analytics + Heatmap del comportamiento cliente","Hosting + dominio + SSL 12 meses","Soporte 30 dias + 2 revisiones incluidas"]'::jsonb,
 '{"client_name":"Casa Marisol (Bilbao)","before":{"reservas_web_mes":0,"conversion_web":"0%","bounce":"82%"},"after":{"reservas_web_mes":147,"conversion_web":"8.3%","bounce":"41%"},"quote":"Antes el movil no paraba los sabados. Ahora 70% reservas entran solas, en frances y aleman. Pable entrego en 14 dias.","disclaimer":"Simulacion basada en promedio restaurante PACAME primeros 90 dias"}'::jsonb,
 149900, 14,
 '[{"q":"¿Puedo integrar TheFork o CoverManager si ya los tengo?","a":"Si, sin problema. Hacemos integracion nativa con TheFork, CoverManager, OpenTable y otros. No pierdes historial ni datos."},{"q":"¿Que pasa con mi carta actual en PDF?","a":"La convertimos a carta digital responsive con fotos HD. Los PDFs de 8MB espantan clientes. Nuestra carta carga en <1s en 4G."},{"q":"¿Los domingos cerrados, como se gestiona?","a":"Configuras horarios y dias cerrados desde panel admin. El sistema bloquea reservas automaticamente."},{"q":"¿Cuantas mesas puedo gestionar?","a":"Ilimitadas. Desde 8 mesas hasta cadena de 20 restaurantes."},{"q":"¿Incluye multi-idioma automatico?","a":"Si, ES/EN/FR incluidos. Pides mas idiomas con coste adicional (DE/IT/PT 99€ c/u)."},{"q":"¿Puedo vender tarjetas regalo?","a":"Si, Stripe integrado. Emite gift cards digitales que tu cliente regala en 3 clicks."},{"q":"¿Y si tengo evento privado?","a":"Bloqueas fecha+mesa desde admin. Tambien puedes activar pagina eventos dedicada."},{"q":"¿Como me llega la reserva?","a":"Email + WhatsApp + notificacion panel. El cliente recibe confirmacion + recordatorio 24h antes."}]'::jsonb,
 '/verticals/restaurante.png',
 'Web para restaurante con reservas online · PACAME · desde 1.499€',
 'Tu restaurante con reservas 24/7, carta digital QR y Google Business integrado. Entrega en 14 dias. 0% comisiones.',
 true, 1),

('restaurante', 'bar-cafeteria', 'Bar / Cafeteria',
 'Bares y cafeterias que quieren vender desayunos, brunch y eventos',
 '☕',
 'Tu bar de especialidad tiene 500 seguidores en Instagram y ninguna venta online',
 '["Subes foto del brunch los domingos pero nadie puede reservarlo","Clientes preguntan en DM por horario, menu, precios — perdes 2h/dia respondiendo","Tu especialidad es tostada de aguacate de 6€ pero compites con Starbucks de 3€ porque no tienes historia","No hay forma de vender cafe en grano o merchandising online","No sabes quien es tu cliente fiel (no tienes CRM)"]'::jsonb,
 'Web mobile-first que transforma Instagram en ventas reales',
 '["Landing con reservas + menu + pedidos para llevar (Stripe)","Click-and-collect: cliente paga, viene y recoge sin cola","Historia de marca (cafes especialidad, origen grano, baristas)","Programa puntos fidelizacion + newsletter","Dark kitchen mode si ofreces delivery"]'::jsonb,
 '["Landing mobile-first con storytelling cafe/brunch","Reservas mesa online 24/7","Click-and-collect con Stripe (paga + recoge sin cola)","Tienda online cafe en grano + merchandising","Menu digital con fotos HD + alergenos + calorias","Programa fidelidad (puntos por visita)","Newsletter + capture email + automatizacion","Integracion Instagram shop (tag products en posts)","Google Business + reseñas + horarios","Hosting + dominio + soporte 30d"]'::jsonb,
 '{"client_name":"Tostaduria Verdi (Madrid)","before":{"pedidos_online_mes":0,"seguidores_ig":520,"ticket_medio":"4,50€"},"after":{"pedidos_online_mes":89,"seguidores_ig":1840,"ticket_medio":"7,80€"},"quote":"La tienda de grano online nos da +400€/mes que no teniamos. Los clientes del brunch ahora reservan antes y pagan mientras llegan.","disclaimer":"Simulacion basada en promedio cafeteria especialidad PACAME primeros 120 dias"}'::jsonb,
 89900, 10,
 '[{"q":"¿Podeis integrar con TPV Square o iZettle?","a":"Si. Sincronizamos inventario bidireccional con Square, iZettle, Agora o Ágora."},{"q":"¿Incluye diseño del menu o uso el mio?","a":"Puedes usar el tuyo o te hacemos uno con tipografia editorial y fotos HD (incluido)."},{"q":"¿Venta de cafe en grano como funciona?","a":"Stripe + envio automatico (Seur/Correos Express). Tu solo empaquetas."},{"q":"¿Programa puntos como se gestiona?","a":"App movil propia con tarjeta fidelizacion digital. Cliente pide desde web o en persona (QR)."},{"q":"¿Puedo limitar pedidos click-and-collect?","a":"Si. Limite slots por hora (ej 10 cafes/30min) para no saturar barra."},{"q":"¿Newsletter automatica?","a":"Mailchimp integrado. 4 plantillas listas: bienvenida, cumpleaños, promocion semanal, nuevos productos."},{"q":"¿Da para varios locales?","a":"Si, multi-local desde panel. Cada local con horario + stock + personal."},{"q":"¿Soporte tecnico cuanto dura?","a":"30 dias incluidos post-entrega. Luego 49€/mes con retencion en panel + Slack."}]'::jsonb,
 '/verticals/restaurante.png',
 'Web para bar o cafeteria con ventas online · PACAME · desde 899€',
 'Reservas + pedidos para llevar + tienda online cafe/merchandising. Convierte Instagram en ingresos reales.',
 true, 2),

('restaurante', 'food-truck', 'Food Truck / Delivery-Only',
 'Negocios gastronomicos sin local fijo que dependen 100% de digital',
 '🚚',
 'Tu food truck cambia de ubicacion cada dia y tus clientes no saben donde estas',
 '["Cada mañana escribes en Instagram donde estaras hoy y se pierde en el feed","Clientes llegan a ubicacion antigua y no vuelven","Sin sitio web tus pedidos a empresa / evento son llamadas a WhatsApp","No captas clientes recurrentes (no hay email, solo DM)","Google no te encuentra porque no tienes web fija"]'::jsonb,
 'Web con geolocalizacion en vivo + pedidos anticipados',
 '["Mapa en vivo: clientes ven donde estas AHORA","Pedidos anticipados: pagan antes, llegan, recogen","Calendario eventos y ubicaciones proximas 30 dias","Formulario cotizacion eventos empresa","CRM clientes recurrentes + SMS marketing"]'::jsonb,
 '["Landing hero con mapa live-tracking Google Maps","Sistema pedidos anticipados con pago Stripe","Calendario publico proximas ubicaciones (30 dias)","Formulario pro: cotizar evento empresa / boda / festival","Panel admin donde cambias ubicacion + menu del dia en 10s","Automatizacion SMS: \"Estamos en Gran Via, pide ya\"","Galeria fotos + videos TikTok embed","Integracion Just Eat / Uber Eats / Glovo si aplica","Hosting + dominio + Google Business","Soporte 30d + revisiones"]'::jsonb,
 '{"client_name":"Bao Truck (Barcelona)","before":{"pedidos_anticipados":0,"eventos_empresa_mes":1,"seguidores_ig":890},"after":{"pedidos_anticipados":124,"eventos_empresa_mes":7,"seguidores_ig":2340},"quote":"El mapa en vivo nos subio pedidos 3x en horas de comida. Los eventos empresa pasaron de 1 a 7 al mes solo por tener formulario pro.","disclaimer":"Simulacion basada en promedio food truck PACAME primeros 90 dias"}'::jsonb,
 79900, 10,
 '[{"q":"¿Como actualizo la ubicacion cada dia?","a":"App movil + panel web. 10 segundos: abres app, marcas punto mapa, guardas. Cliente ve actualizacion inmediata."},{"q":"¿Integra con Just Eat / Uber Eats?","a":"Si. Los enlazamos para que cliente reserve directamente desde tu web."},{"q":"¿SMS marketing incluido?","a":"Si (100 SMS/mes incluidos). Mas con coste 9€/500 SMS."},{"q":"¿Puedo tener varios food trucks?","a":"Si, multi-truck con ubicacion independiente cada uno."},{"q":"¿Permite pedidos grupales?","a":"Si. Cliente elige 5 bao + 3 bebidas. Paga total. Recoge."},{"q":"¿Y si quiero festival / evento especial?","a":"Pagina evento dedicada con venta anticipada tickets si aplica."},{"q":"¿Google Business cambia ubicacion?","a":"Lo optimizamos para busquedas tipo \"food truck cerca de mi\" + eventos especificos (Gran Via, Paseo Gracia)."},{"q":"¿Funciona sin cobertura movil en festival?","a":"Modo offline: tomas pedido local, sincroniza al recuperar 4G."}]'::jsonb,
 '/verticals/restaurante.png',
 'Web para food truck con mapa live · PACAME · desde 799€',
 'Geolocalizacion en vivo + pedidos anticipados + formulario eventos empresa. Entrega 10 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: HOTEL
-- ══════════════════════════════════════════════════════════════════════════
('hotel', 'hotel-boutique', 'Hotel Boutique',
 'Hoteles 4-5* independientes que compiten con Booking.com por comision directa',
 '🏨',
 'Booking.com se lleva 18% de cada reserva y tu web directa convierte <1%',
 '["Cada reserva en Booking = pierdes 18% comision = 30-45€ por noche","Tu web directa recibe 10% del trafico y convierte <1% (industria media 4%)","No tienes motor reservas propio competitivo — cliente compara y gana Booking","Fotos de Booking son mejores que las tuyas (te toman tu identidad)","Reviews dispersas: TripAdvisor, Booking, Google, sin centralizar"]'::jsonb,
 'Web de autor con motor reservas directo + programa fidelizacion',
 '["Motor reservas directo con Stripe (SIN comision)","Pricing dinamico + ofertas exclusivas solo web","Programa socio VIP: reserva directa = 10% descuento + upgrade","Photo story cinematografico que Booking no puede copiar","Multi-idioma ES/EN/FR/DE incluidos + geo-pricing por pais"]'::jsonb,
 '["Diseño cinematografico editorial (inspiracion Aman, Soho House)","Motor reservas propio + Stripe + IATA integration opcional","Multi-idioma ES/EN/FR/DE + geo-pricing por origen","Programa socio VIP con descuentos directos","Integracion Channel Manager (Siteminder, Cloudbeds, Mews)","Sistema reviews centralizado (TripAdvisor + Google + Booking)","Concierge digital: reservar actividades, spa, transfer","Blog viaje con SEO local (10 posts iniciales)","Email automation: confirmacion, pre-stay, post-stay, review","Dashboard admin + analytics + occupancy"]'::jsonb,
 '{"client_name":"Hotel Maison Ondara (Alicante)","before":{"reservas_directas_mes":12,"comision_Booking_mes":"4.800€","web_conversion":"0.8%"},"after":{"reservas_directas_mes":67,"comision_Booking_mes":"1.900€","web_conversion":"3.4%"},"quote":"Ahorramos 2.900€ al mes solo en comisiones Booking. El programa socio VIP convirtio 40% de clientes Booking en directos.","disclaimer":"Simulacion basada en promedio hotel boutique PACAME primeros 180 dias"}'::jsonb,
 349900, 21,
 '[{"q":"¿Integrais con channel manager si ya tenemos?","a":"Si: Siteminder, Cloudbeds, Mews, Hotelogix. Sincronizacion inventario bidireccional 24/7."},{"q":"¿Cuanto ahorramos en comisiones Booking?","a":"Clientes promedio ahorran 40-60% via reservas directas tras 6 meses. En hoteles 30+ hab, son 5.000-15.000€/mes en comisiones."},{"q":"¿Programa socio VIP como se configura?","a":"Cliente reserva directa = automaticamente socio. Beneficios: 10% off, upgrade sujeto disponibilidad, early check-in, welcome drink."},{"q":"¿Multi-idioma con traducciones automaticas?","a":"No automaticas. Incluimos traduccion profesional ES/EN/FR/DE por copywriter nativo (no Google Translate)."},{"q":"¿Geo-pricing que es?","a":"Precios diferenciados por pais origen (visitante UK ve £, frances ve precio EUR con ajuste tipo cambio)."},{"q":"¿Podemos vender extras (spa, desayuno)?","a":"Si. Upsell en checkout + en email pre-stay. Cross-sell aumenta ticket medio ~30%."},{"q":"¿Reviews centralizadas como?","a":"Widget que muestra reviews top de TripAdvisor + Google + Booking. Cliente ve score agregado (ej 4.7/5 de 450 reviews)."},{"q":"¿Y si ya tengo web?","a":"Migramos todo sin perder SEO (301 redirects + sitemap nuevo). Lanzamos en subdominio stage primero."}]'::jsonb,
 '/verticals/hotel.png',
 'Web para hotel boutique con motor reservas directo · PACAME · desde 3.499€',
 'Ahorra 40-60% comisiones Booking. Motor reservas propio + programa VIP + multi-idioma. Entrega 21 dias.',
 true, 1),

('hotel', 'hostel', 'Hostel / Albergue',
 'Hostales y albergues para backpackers, grupos y familias jovenes',
 '🛏️',
 'Tu hostel compite con 50 mas en Hostelworld y convierte en base a precio',
 '["Hostelworld se lleva 10-15% + precios comparables todos","Backpacker medio reserva 48h antes = dependes 100% OTAs","No captas travelers que vienen por eventos locales (festivales, conciertos)","Sin experiencia digital unica (todos los hostels lucen igual)","No puedes vender experiencias (tours, bike rental, bar crawl)"]'::jsonb,
 'Web vibrante con reservas directas + experiencias + comunidad',
 '["Motor reservas directo Stripe sin comision","Seccion experiencias: tours, bike rental, bar crawl, cooking classes","Blog local \"What to do in [ciudad]\" con SEO eventos","Integracion Instagram / TikTok embeds","Programa referido: 10€ credito por amigo que reserva"]'::jsonb,
 '["Diseño joven energetico + fotos lifestyle","Motor reservas habitaciones + camas dormitorio","Catalogo experiencias vendibles (tours, actividades)","Blog SEO local eventos (festivales, conciertos)","Integracion Instagram shop + UGC (contenido usuarios)","Sistema referidos + codigo descuento","Multi-idioma ES/EN/FR/DE/IT","Chat en vivo + WhatsApp","Integracion Hostelworld, Booking (bidireccional)","Mapa barrio con spots recomendados"]'::jsonb,
 '{"client_name":"Urban House Hostel (Sevilla)","before":{"reservas_directas_mes":8,"upsell_experiencias":"0€","review_hostelworld":8.6},"after":{"reservas_directas_mes":54,"upsell_experiencias":"1.840€","review_hostelworld":9.1},"quote":"Los tours de tapas y flamenco generan 1.800€/mes extra. Y los clientes reservan directo porque la web es mas cool que Hostelworld.","disclaimer":"Simulacion basada en promedio hostel PACAME primeros 120 dias"}'::jsonb,
 179900, 14,
 '[{"q":"¿Como gestiono disponibilidad entre dormitorios y privadas?","a":"Panel admin unico con inventario cama-a-cama. Sincronizado Hostelworld/Booking automatico."},{"q":"¿Experiencias son propias o externas?","a":"Ambas. Propias (tu organizas) o externas (comision 20-30% al proveedor)."},{"q":"¿Referidos como funciona?","a":"Cliente genera codigo unico. Amigo reserva con codigo = 10€ off al amigo + 10€ credito al referente."},{"q":"¿Integra chat en vivo?","a":"Si. Intercom/Crisp o widget propio. Puedes responder desde movil."},{"q":"¿Blog local eventos?","a":"Si. 10 posts iniciales incluidos (\"Top 5 festivales Sevilla 2026\", \"Mejores bares tapas\"). SEO organico backpackers."},{"q":"¿Podemos vender pack largo? (7+ noches)","a":"Si. Pricing escalonado automatico: 7+ noches = 10% off, 14+ = 15% off."},{"q":"¿Multi-idioma critico?","a":"Absoluto. 60% de tu audiencia es extranjera. ES/EN/FR/DE/IT incluidos, traduccion copywriter."},{"q":"¿Como compito con Selina o Generator?","a":"Con personalidad local. Esas cadenas son genericas. Tu historia + barrio + staff son tu ventaja — la web la cuenta."}]'::jsonb,
 '/verticals/hotel.png',
 'Web para hostel con reservas directas + experiencias · PACAME · desde 1.799€',
 'Motor reservas sin comision + tours vendibles + SEO local. Captura backpackers antes que Hostelworld.',
 true, 2),

('hotel', 'apartamentos-turisticos', 'Apartamentos Turísticos / Airbnb Owner',
 'Propietarios Airbnb con 1-20 apartamentos que quieren reservas directas',
 '🔑',
 'Airbnb se lleva 14-20% de comision + controla tu relacion con huespedes',
 '["14-20% comision Airbnb = si facturas 50k/año, pierdes 7-10k","Airbnb oculta datos huesped, no puedes fidelizar ni remarketear","Competencia creciente: nuevos hosts bajan precios — tu te ves forzado a bajar","Reviews Airbnb unicas visibles en Airbnb (no ayudan fuera)","Cargos extra (limpieza, deposito) se ven feos en cobro final Airbnb"]'::jsonb,
 'Web directa con cobro propio + tu marca + fidelizacion',
 '["Reserva directa sin comision (solo Stripe 1.4%)","Tu marca, tu tono, tu historia (no Airbnb Template)","Programa cliente recurrente: 2a estancia = 10% off","Multi-calendario integrado con Airbnb/Vrbo (no bookings duplicados)","Email + WhatsApp automation: pre-stay, check-in, post-stay, review"]'::jsonb,
 '["Diseño premium tipo Airbnb pero TU marca","Motor reservas con Stripe (1.4% vs 14% Airbnb)","iCal sync bidireccional Airbnb + Vrbo + Booking","Cobro deposito + limpieza separados + opcional","Check-in digital (guest envia DNI, recibe codigo acceso)","Guide del barrio personalizada (PDF descargable o pagina web)","Email + WhatsApp automation 5 secuencias","Dashboard admin ocupacion + revenue + ADR","Multi-idioma ES/EN/FR + multi-moneda","Traduccion copywriter nativo + fotos editing pro"]'::jsonb,
 '{"client_name":"Ondara Apartments (Madrid, 4 apts)","before":{"comision_Airbnb_año":"8.200€","reservas_directas_mes":1,"tasa_repetidores":"8%"},"after":{"comision_Airbnb_año":"3.100€","reservas_directas_mes":14,"tasa_repetidores":"23%"},"quote":"Pague 2.499€ una vez y ahorre 5.100€ en comisiones en el primer año. Los clientes vuelven porque los tengo en mi email, no en Airbnb.","disclaimer":"Simulacion basada en promedio propietario 4 apartamentos PACAME año 1"}'::jsonb,
 249900, 18,
 '[{"q":"¿Airbnb me puede penalizar por tener web propia?","a":"No. Airbnb prohibe enviar clientes SUYOS fuera. Pero atraer clientes NUEVOS a tu web es legal y recomendado."},{"q":"¿Perderia disponibilidad en Airbnb?","a":"No. iCal sync bidireccional. Reserva web = se bloquea Airbnb. Reserva Airbnb = se bloquea web. Cero bookings duplicados."},{"q":"¿Stripe vs Airbnb cobro? ¿Es seguro?","a":"Absolutamente. Stripe es PCI-DSS, usado por Shopify, Booking. Cliente paga tranquilo con Apple Pay/Visa/Mastercard."},{"q":"¿Cuanto es el costo real?","a":"Stripe: 1.4% + 0.25€. Hosting: 20€/mes incluido primer año. Resto no tiene comisiones ni mensualidades ocultas."},{"q":"¿Como evito check-in tedioso?","a":"Check-in digital: huesped envia DNI/pasaporte 24h antes. Recibe codigo acceso caja fuerte o cerradura smart. Ley EES compliant."},{"q":"¿Multi-apartamento desde un panel?","a":"Si. 1 a 50 apartamentos gestionados desde un solo panel. Cada uno su calendario, precio, fotos, guide."},{"q":"¿Podemos vender extras? (limpieza extra, transfer, cesta bienvenida)","a":"Si. Upsell en checkout + email pre-stay. Margen 100% tuyo, no comision a nadie."},{"q":"¿Incluye SEO local?","a":"Si. Landing dedicada por barrio (\"Apartamento Malasaña\", \"Apartamento Gracia\") con SEO local para rankear Google."}]'::jsonb,
 '/verticals/hotel.png',
 'Web para apartamentos turisticos sin comision Airbnb · PACAME · desde 2.499€',
 'Ahorra 14-20% de Airbnb. Reservas directas con tu marca, iCal sync, programa fidelizacion. Entrega 18 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: CLINICA
-- ══════════════════════════════════════════════════════════════════════════
('clinica', 'clinica-privada', 'Clinica Privada (General)',
 'Clinicas privadas medicas con 2-10 especialistas',
 '🏥',
 'Tus pacientes llaman por telefono y la recepcion pasa 4h/dia al telefono',
 '["Telefono ocupado = pacientes buscan otra clinica","Recepcion contesta 80 llamadas/dia, cansancio + errores","Pacientes nuevos buscan en Google, ven ficha vacia, eligen competencia","No puedes mostrar tus especialistas con fotos + perfiles profesionales","Sin historial digital, cada visita empieza desde cero"]'::jsonb,
 'Web profesional con cita online + portal paciente',
 '["Cita online 24/7 con calendario por especialista","Portal paciente: historial, facturas, proximas citas","Fichas especialistas con CV, titulaciones, idiomas","Recordatorios automaticos email + SMS (reducen no-show 60%)","Integracion sistemas medicos (Doctoralia, Docplanner, propios)"]'::jsonb,
 '["Diseño confianza medica (paleta Ocean + Mint)","Cita online integrada con calendario especialista","Portal paciente seguro (login + historial + facturas)","Fichas especialista con fotos + CV + especialidades + idiomas","Sistema recordatorios email + SMS (reducen no-show)","Pagina por especialidad optimizada SEO local","Integracion Google Business + reviews agregadas","Multi-idioma ES/EN (pacientes internacionales)","RGPD + LOPDGDD compliance total","Hosting medico HIPAA-compliant + backups diarios"]'::jsonb,
 '{"client_name":"Centro Medico Arco Iris (Valencia)","before":{"llamadas_dia":78,"no_show":"18%","citas_online":0},"after":{"llamadas_dia":23,"no_show":"6%","citas_online":124},"quote":"Recepcion respira. Las citas online son 50% del total. El no-show bajo de 18% a 6% con los recordatorios SMS.","disclaimer":"Simulacion basada en promedio clinica PACAME primeros 90 dias"}'::jsonb,
 219900, 18,
 '[{"q":"¿Como integra con nuestro historial?","a":"Tenemos conectores con Doctoralia, Docplanner, CasiCas, propios. Sync bidireccional historial + citas."},{"q":"¿Cumple RGPD y LOPDGDD?","a":"Si. Encriptacion E2E, hosting UE, consentimientos explicitos, logs auditoria. Incluye DPO-asistencia inicial."},{"q":"¿Cuantos especialistas soporta?","a":"Ilimitados. Cada uno su calendario, especialidad, horario, tarifa."},{"q":"¿Los recordatorios SMS cuestan?","a":"Primeros 500/mes incluidos. Despues 9€/1.000 SMS."},{"q":"¿Portal paciente es seguro?","a":"Login 2FA + encriptacion + sesiones timeout. Homologado para datos sensibles medicos."},{"q":"¿Puedo vender bonos consultas?","a":"Si. Stripe + control uso. Paciente compra \"Bono 10 sesiones\", cada cita resta 1."},{"q":"¿Integra con Siemens/MySpring/Otros?","a":"Si. Integraciones custom disponibles (coste adicional segun complejidad)."},{"q":"¿Facturacion electronica?","a":"Si. Factura se envia automatica tras consulta. Formato Facturae compatible AEAT."}]'::jsonb,
 '/verticals/clinica.png',
 'Web para clinica privada con cita online y portal paciente · PACAME · desde 2.199€',
 'Cita 24/7 + portal paciente + recordatorios SMS. Reduce no-show 60%. Entrega 18 dias. RGPD compliant.',
 true, 1),

('clinica', 'dentista', 'Clinica Dental',
 'Clinicas dentales que quieren captar pacientes nuevos online',
 '🦷',
 'El 80% de los pacientes dentales buscan en Google antes de elegir',
 '["Buscan \"dentista [ciudad]\" y tu clinica no aparece en top 3","Ficha Google sin fotos de clinica ni reviews = pierden confianza","No pueden ver precios ni tratamientos = 70% no llaman","Ortodoncia invisible Invisalign es decision compra de 3.000€+ — necesitan ver casos","La competencia tiene web con antes/despues, tu no"]'::jsonb,
 'Web dental premium con galeria casos + calculadora Invisalign',
 '["Galeria casos reales antes/despues (con consentimiento)","Calculadora Invisalign online (input: dientes, plan, precio estimado)","Cita online por especialidad (ortodoncia, estetica, implantes)","SEO local dominante para \"dentista [ciudad]\"","Blog con guias: \"5 señales Invisalign\", \"Cuanto cuesta blanqueamiento\""]'::jsonb,
 '["Diseño premium estetica dental + confianza clinica","Galeria casos reales con slider antes/despues","Calculadora Invisalign / ortodoncia / implantes online","Cita online con especialista por tratamiento","SEO local con 10 articulos guia","Fichas tratamiento con fotos + precios desde + duracion","Reviews agregadas Google + Doctoralia","Financing integrado (Cetelem/Cofidis/ProMedical)","Chat en vivo + WhatsApp Business","Video tour clinica (fotos clinica + equipamiento)"]'::jsonb,
 '{"client_name":"Clinica Dental Sonrisa (Zaragoza)","before":{"nuevas_citas_mes":18,"ingreso_medio_nuevo":"180€","calculadora_Invisalign":"N/A"},"after":{"nuevas_citas_mes":63,"ingreso_medio_nuevo":"740€","calculadora_Invisalign":"34 leads/mes"},"quote":"La calculadora Invisalign genera 34 leads cualificados al mes. De esos, 12 contratan (34% conversion). 50k€ de ingresos NUEVOS al año por la web.","disclaimer":"Simulacion basada en promedio clinica dental PACAME primeros 180 dias"}'::jsonb,
 199900, 18,
 '[{"q":"¿Galeria antes/despues legal?","a":"Si, con consentimiento firmado paciente. Incluimos modelo consentimiento RGPD compliant."},{"q":"¿Calculadora Invisalign como funciona?","a":"Paciente selecciona problema (dientes apiñados, espaciados, mordida cruzada) + plan. Devuelve precio estimado y slots cita. Lead cualificado."},{"q":"¿Financing integrado real?","a":"Si. Cetelem, Cofidis o ProMedical. Paciente ve cuota mensual directamente (\"Desde 99€/mes\")."},{"q":"¿SEO local lleva cuanto?","a":"Primeras posiciones Google: 3-6 meses con blog + optimizacion. Top 3 alcanzable mes 4."},{"q":"¿Video tour clinica?","a":"Lo grabamos con movil o camara profesional (coste extra). O usas tuyos. Nosotros editamos."},{"q":"¿Chat vs WhatsApp Business?","a":"Ambos. Chat web captura visitantes activos, WhatsApp para pacientes con preguntas especificas."},{"q":"¿Puedo vender bonos?","a":"Si. Bono \"10 sesiones blanqueamiento\" + Stripe + panel uso."},{"q":"¿Reviews Doctoralia?","a":"Las integramos en tu web (widget). Cada 5 reviews incrementa conversion +15% estudios."}]'::jsonb,
 '/verticals/clinica.png',
 'Web para clinica dental con calculadora Invisalign · PACAME · desde 1.999€',
 'Calculadora tratamiento + galeria casos + cita online. Capta pacientes Invisalign cualificados. Entrega 18 dias.',
 true, 2),

('clinica', 'fisioterapeuta', 'Fisioterapeuta / Clinica Fisio',
 'Fisioterapeutas independientes o clinicas pequeñas',
 '🦴',
 'Tus pacientes tardan 2-3 semanas en pedir cita (dolor cronico, no urgente)',
 '["Paciente posterga cita hasta que el dolor es incapacitante","Sin cita online, llaman solo cuando el dolor es 10/10 = peor pronostico","No puedes ofrecer planes (\"10 sesiones recuperacion\") claros online","Competencia con fisio Instagram tiene mas seguidores y clientes","Paciente no sabe si debe venir por ese dolor especifico"]'::jsonb,
 'Web con triaje digital + plan pacientes + contenido educativo',
 '["Triaje inicial gratis: \"¿Tu dolor es urgente?\" cuestionario 5 preguntas","Planes de recuperacion visibles (5, 10, 15 sesiones con pricing)","Video biblioteca ejercicios segun diagnostico","Cita online + opcion primera visita gratis","Blog SEO con contenido educativo por zona cuerpo"]'::jsonb,
 '["Diseño limpio enfoque clinico + confianza","Triaje inicial cuestionario 5 preguntas (lead magnet)","Planes sesiones visibles con pricing y duracion","Cita online por especialidad (deporte, suelo pelvico, ancianos)","Biblioteca ejercicios en video por diagnostico","Blog SEO 10 articulos: lumbalgia, cervicales, running","Testimonios pacientes (video opcional)","Integracion Google Business + reviews","Financing planes largos (Cetelem)","Newsletter + email automation pre-cita"]'::jsonb,
 '{"client_name":"Fisioterapia Activa (Bilbao)","before":{"citas_nuevas_mes":22,"conversion_web":"2%","venta_bonos":0},"after":{"citas_nuevas_mes":58,"conversion_web":"6.8%","venta_bonos":"4.200€/mes"},"quote":"El triaje convirtio visitantes en leads. La venta de bonos \"10 sesiones\" nos da 4.200€/mes que antes no teniamos.","disclaimer":"Simulacion basada en promedio fisio PACAME primeros 120 dias"}'::jsonb,
 139900, 14,
 '[{"q":"¿Triaje tiene responsabilidad legal?","a":"No es diagnostico medico. Es orientacion. Incluimos disclaimer claro y no damos recomendacion clinica, solo urgencia."},{"q":"¿Video ejercicios los grabo yo?","a":"Puedes usar los tuyos. O te damos guion + template para grabar en 2h con el movil."},{"q":"¿Bonos sesiones vs pago por sesion?","a":"Los bonos (5/10/15 sesiones) convierten 3x mejor porque el paciente decide una vez y no tiene \"momento de decision\" cada semana."},{"q":"¿Financing para planes 15+ sesiones?","a":"Si. Cetelem o pago en 3/6/12 meses con 0% interes (asumes tu coste o pasas al paciente)."},{"q":"¿Blog SEO tengo que escribirlo yo?","a":"No. 10 posts iniciales incluidos. Luego te damos calendario + templates para seguir."},{"q":"¿Multi-fisio desde el panel?","a":"Si. Cada fisio con su calendario, especialidad, tarifa, sesiones disponibles."},{"q":"¿Puedo vender tienda productos?","a":"Si. Tienda integrada Stripe para vender pelotas terapeuticas, bandas, libros."},{"q":"¿Primera visita gratis como se controla?","a":"Codigo promocional aplicable 1 vez por email. Genera lead + paciente prueba."}]'::jsonb,
 '/verticals/clinica.png',
 'Web para fisioterapeuta con triaje digital y bonos · PACAME · desde 1.399€',
 'Triaje inicial + planes sesiones + biblioteca ejercicios. Convierte visitantes en pacientes. Entrega 14 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: GYM
-- ══════════════════════════════════════════════════════════════════════════
('gym', 'gimnasio', 'Gimnasio / Centro Fitness',
 'Gimnasios tradicionales con 200+ socios activos',
 '🏋️',
 'Tus socios se dan de baja despues de 3 meses y no sabes por que',
 '["Tasa churn 40% anual = cada año perdes la mitad de tus socios","No conoces motivaciones (peso? fuerza? social?) no puedes retener","Sin clases online, pierden motivacion el dia que no vienen","Tu app actual de 2018 nadie la usa","Competencia low-cost rodea tu zona (Altafit, Anytime Fitness)"]'::jsonb,
 'Web + app PWA + sistema retencion con clases online y gamification',
 '["Web + PWA que se instala como app nativa sin App Store","Inscripcion online con prueba gratis 7 dias","Calendario clases en vivo + on-demand","Sistema gamification: puntos + badges + leaderboard","Retencion automation: \"No te vemos hace 2 semanas, te echamos de menos\""]'::jsonb,
 '["Diseño energetic enfoque transformacion","PWA instalable (iOS + Android, sin app store)","Inscripcion online con prueba 7 dias gratis + Stripe","Calendario clases grupales con inscripcion/cancelacion","Biblioteca clases on-demand (yoga, HIIT, fuerza)","Sistema puntos + badges + leaderboard mensual","Retencion automation (email + push si lleva X dias sin venir)","Tienda ropa deportiva + suplementos","Integracion control acceso (huella, QR, NFC) opcional","Panel admin con metricas retencion, ocupacion, churn"]'::jsonb,
 '{"client_name":"Active Gym (Sevilla)","before":{"churn_anual":"42%","socios_activos":210,"clases_online":0},"after":{"churn_anual":"26%","socios_activos":287,"clases_online":"48% socios usan"},"quote":"La gamification cambio todo. Los socios compiten entre ellos y quieren venir. El churn bajo 16 puntos.","disclaimer":"Simulacion basada en promedio gimnasio PACAME año 1"}'::jsonb,
 269900, 21,
 '[{"q":"¿PWA vs app nativa? ¿Hay diferencia?","a":"Minima. PWA instala desde Chrome/Safari como app, sin pasar App Store/Play. Ahorras 300€/año de Apple Developer + 25€ Google."},{"q":"¿Clases online en vivo como?","a":"Integracion Zoom o Whereby. Socio entra con un click desde la app."},{"q":"¿Gamification real mejora retencion?","a":"Si. Estudios industria: gyms con gamification retienen 30% mas a 12 meses. Competir con amigos = motivacion."},{"q":"¿Integra con mi control de acceso actual?","a":"Depende. Con Gantner, Nexus, Dom4L tenemos integraciones hechas. Otros = 1-2 semanas trabajo."},{"q":"¿Tienda ropa y suplementos?","a":"Si. Stripe + dropshipping o tu stock. Cross-sell al socio existente convierte 20%+ porque ya confia."},{"q":"¿Multi-club?","a":"Si. Socio Multi-club paga una cuota y accede a tus N gimnasios. Panel central."},{"q":"¿Personal trainers se integran?","a":"Si. Cada entrenador con su calendario clases 1-on-1 + comision automatica."},{"q":"¿Cuanto tiempo ROI?","a":"Clientes promedio recuperan inversion en 3-4 meses con reduccion churn + ventas nuevas (inscripcion online)."}]'::jsonb,
 '/verticals/gym.png',
 'Web + PWA para gimnasio con gamification · PACAME · desde 2.699€',
 'App instalable + clases online + sistema retencion. Baja churn 16 puntos promedio. Entrega 21 dias.',
 true, 1),

('gym', 'entrenador-personal', 'Entrenador Personal',
 'Entrenadores independientes que venden sesiones 1-on-1 + programas online',
 '💪',
 'Vendes tiempo (sesiones) y tu techo de ingresos es 8h de entrenamiento/dia',
 '["Limitas ingresos a horas disponibles = max 4.000€/mes","Cada cliente te paga igual sin importar experiencia = sin premium","No vendes programas online que escalan","Tus redes tienen 5k seguidores y ninguno paga","Cobras en efectivo/Bizum sin facturas = riesgo hacienda"]'::jsonb,
 'Web + app con sesiones 1-on-1 + programas online + comunidad',
 '["Sesiones 1-on-1 con pricing premium (tiers: junior/senior/elite)","Programas online escalables: cliente paga 199€ por 8 semanas","Comunidad privada con plan mensual (49€/mes, 100 clientes = 4.900€/mes)","App con tracking: fotos progreso, medidas, nutricion","Faturacion automatica Stripe (adios efectivo)"]'::jsonb,
 '["Landing personal storytelling (tu historia, filosofia, resultados)","Sistema sesiones 1-on-1 con Stripe + calendario","Venta programas online autoreproducibles (8-12 semanas)","Comunidad privada tipo Slack/Discord con plan mensual","App tracking progreso: peso, medidas, fotos (privadas)","Videoteca ejercicios + programa nutricion","Comunidad con foro + retos semanales + leaderboard","Integracion Instagram / TikTok para conversion","Facturacion automatica Stripe + Facturae AEAT","Analytics ingresos: por cliente, por programa, por canal"]'::jsonb,
 '{"client_name":"Marta Oliveira Fit (Madrid)","before":{"ingresos_mes":"2.800€","clientes":15,"programas_online":0},"after":{"ingresos_mes":"8.400€","clientes_1on1":18,"programas_online":"67 vendidos","comunidad_miembros":42},"quote":"Vendo mi programa de 8 semanas a 199€ en piloto automatico. Mi comunidad privada genera 2.000€/mes pasivos. Pase de 2.8k a 8.4k sin trabajar mas horas.","disclaimer":"Simulacion basada en promedio entrenador personal PACAME año 1"}'::jsonb,
 129900, 12,
 '[{"q":"¿Programa online se graba una vez y vende infinito?","a":"Exacto. Grabas 8-12 clases (2-3h trabajo), montas la estructura en plataforma, vendes 100 veces sin trabajo extra."},{"q":"¿Comunidad privada vs Discord gratis?","a":"Discord tiene 0% conversion. Tu plataforma propia con pago mensual = barrera entrada + sense of value. Miembros pagan = participan."},{"q":"¿Stripe para recurrentes?","a":"Si. Mensual, anual, pausa, cancelacion. Todo automatico sin que tu intervengas."},{"q":"¿App Native real o PWA?","a":"PWA. Se instala desde movil como nativa sin App Store. Costo 0 vs 300€/año Apple."},{"q":"¿Facturacion automatica como?","a":"Cliente paga -> Stripe emite factura en tu nombre con tus datos fiscales -> envia PDF a email cliente + copia a ti. Sin clicks."},{"q":"¿Puedo vender suplementacion?","a":"Si. Tienda integrada. Dropshipping (MyProtein, Prozis) o stock propio."},{"q":"¿Integra con Instagram?","a":"Si. Link in bio + shoppable posts + historias con swipe up a landing conversion."},{"q":"¿Y si tengo 50+ clientes online? ¿Soporte?","a":"Panel admin filtra clientes por estado, pago, actividad. Automation envia mensaje segun comportamiento."}]'::jsonb,
 '/verticals/gym.png',
 'Web + app para entrenador personal · PACAME · desde 1.299€',
 'Sesiones 1-on-1 + programas online escalables + comunidad mensual. Escala ingresos sin mas horas. Entrega 12 dias.',
 true, 2),

('gym', 'crossfit-box', 'CrossFit Box / Boutique Fitness',
 'Boxes de CrossFit, HIIT, Pilates, Yoga estudio',
 '🔥',
 'Tu box compite con gyms low-cost por precio y no destacas tu comunidad',
 '["Prospecto compara tu box con gym 19€/mes — no ve diferencia","No puedes mostrar intensidad sesiones (videos WOD, PRs, eventos)","Inscripcion 1er workout gratis es por llamada/email = fricciona","Sin leaderboard digital, la competencia interna se pierde","Competiciones internas (CrossFit Total, Open Prep) no las vendes online"]'::jsonb,
 'Web con comunidad + WOD del dia + leaderboard + competiciones',
 '["Prueba 7 dias gratis con inscripcion 1 click","WOD del dia en vivo: publicado cada mañana, video del coach","Leaderboard mensual por categoria (Rx, Scaled, Master)","Venta eventos: Competicion interna, Hero WOD, Seminarios","Comunidad atletas con fotos PRs + badges"]'::jsonb,
 '["Diseño intensidad enfoque comunidad","WOD del dia con descripcion + movimientos + demo video","Leaderboard mensual por categoria","Inscripcion clase online (limite plazas por sesion)","Venta eventos / competiciones / seminarios","Biblioteca WODs anteriores con filtro (fuerza, metcon, skill)","Perfil atleta con PRs personales + badges","Tienda merchandising + suplementacion","Integracion Wodify / BTWB (opcional)","Certificaciones coaches visibles"]'::jsonb,
 '{"client_name":"Box Vikings (Pamplona)","before":{"inscripciones_prueba_mes":8,"eventos_vendidos":0,"retencion_3m":"58%"},"after":{"inscripciones_prueba_mes":34,"eventos_vendidos":"6 al año","retencion_3m":"81%"},"quote":"La prueba gratis 1-click triplico inscripciones. Los eventos pagan solos — 6 al año generan 8.400€ extra. El leaderboard hace que vuelvan por la comunidad.","disclaimer":"Simulacion basada en promedio box CrossFit PACAME año 1"}'::jsonb,
 189900, 16,
 '[{"q":"¿WOD diario lo publicamos nosotros o ustedes?","a":"Tu. Panel admin con template — 2 min por WOD. Alternativa: te programamos 12 meses WODs (servicio aparte)."},{"q":"¿Leaderboard vs BTWB / Wodify?","a":"Funcional propio. Si ya usas BTWB/Wodify, integramos (coste extra). Solo funcional propio basta para box pequeño/mediano."},{"q":"¿Inscripcion con limite plaza como?","a":"Clase 18h: 12 plazas. Cuando llega #12, aparece \"Completo\" + lista espera automatica."},{"q":"¿Tienda merchandising ilimitada?","a":"Si. Stripe + inventario. Vendes ropa, camisetas del box, suplementos, equipamiento propio."},{"q":"¿Certificaciones coaches como?","a":"Ficha coach con foto + bio + cert CF-L1/L2/L3 + especialidades. Refuerza autoridad percibida."},{"q":"¿Seminarios externos?","a":"Si. Venta tickets online + limite plazas + seating chart opcional (si lo necesitas)."},{"q":"¿Y Hero WODs?","a":"Pagina dedicada Hero WODs (Murph, Fran, etc) con historia + record box + eventos programados."},{"q":"¿Integra con control acceso huella?","a":"Si en algunos casos. Depende del sistema que uses (Gantner, Nexus tienen API)."}]'::jsonb,
 '/verticals/gym.png',
 'Web para box CrossFit con comunidad y eventos · PACAME · desde 1.899€',
 'WOD diario + leaderboard + eventos vendibles. Triplica inscripciones prueba. Entrega 16 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: INMOBILIARIA
-- ══════════════════════════════════════════════════════════════════════════
('inmobiliaria', 'inmobiliaria', 'Inmobiliaria / Agencia',
 'Inmobiliarias con 50-500 propiedades y 3-10 agentes',
 '🏢',
 'Idealista se lleva tus leads y te cobra 300-800€/mes por aparecer',
 '["Listados Idealista = comoditizados. Cliente no distingue tu agencia","Cada lead Idealista te cuesta 50-100€, no recurrente","Tu web no es discoverable en Google (SEO local) = dependes Idealista","No tienes embudo: lead entra, pide info, sale, no vuelves a hablar","Competidor grande (Tecnocasa, Remax) tiene portal nacional = credibilidad"]'::jsonb,
 'Portal propio con SEO dominante + CRM + app agentes',
 '["Portal propietario con 500+ propiedades + filtros avanzados","SEO local dominante (\"piso Malasana\", \"chalet Sant Cugat\")","CRM integrado: lead entra, agente asignado automatico, automation seguimiento","App agentes con fichas + fotos + agenda","Landing por barrio con estadisticas mercado y tu ofertas"]'::jsonb,
 '["Diseño profesional + fotos HD propietarias","Catalogo 500+ propiedades con filtros (precio, zona, m2, habs)","Buscador mapa + geolocalizacion + tours virtuales 360","Landing por zona con SEO local + estadisticas mercado","CRM integrado: asignacion auto leads + automation","App agentes iOS + Android (PWA) con fichas clientes","Automatizacion: email seguimiento tras visita, aniversario compra, refer a friend","Integracion portales externos (Idealista sync, Fotocasa export)","Blog SEO local mercado (15 articulos iniciales)","Reports mensuales: visitas web, leads, conversiones por agente"]'::jsonb,
 '{"client_name":"Inmobiliaria Gadira (Malaga)","before":{"leads_web_mes":12,"leads_Idealista_mes":"45 pero 78€ cada","tiempo_respuesta_lead":"8h"},"after":{"leads_web_mes":187,"leads_Idealista_mes":"reducido 40%","tiempo_respuesta_lead":"2min automation"},"quote":"Pasamos de depender 90% Idealista a 30%. El CRM con automation nos responde en 2 minutos y cerramos 3x mas. El SEO local nos posiciono top 3 en 4 meses.","disclaimer":"Simulacion basada en promedio inmobiliaria PACAME año 1"}'::jsonb,
 399900, 28,
 '[{"q":"¿Sync con Idealista / Fotocasa?","a":"Si. Actualizas propiedad en tu panel, se exporta a Idealista/Fotocasa/Habitaclia automaticamente. Sin duplicacion trabajo."},{"q":"¿Tours virtuales 360 incluidos?","a":"Si, rendering del tour (Matterport). Tu capturas con camara/movil, nosotros integramos en ficha."},{"q":"¿CRM vs Inmovilla o Witei?","a":"Propio incluido. Si ya usas Inmovilla/Witei, integramos (1 semana trabajo extra)."},{"q":"¿SEO local cuanto tarda?","a":"Top 10 en 2-3 meses. Top 3 en 4-6 meses. Consistencia blog + optimizacion on-page + link building local."},{"q":"¿Automation tras visita?","a":"Email 1h post-visita: \"¿Que te parecio?\". Email 3 dias: \"Otras 3 similares\". Email 2 semanas: \"Abrimos nuevas en la zona\"."},{"q":"¿App agentes sync con CRM?","a":"Si. Ficha cliente, proximas visitas, notas, documentos — todo sync bidireccional."},{"q":"¿Multi-oficina?","a":"Si. N oficinas con N agentes cada una. Reports y comisiones separadas."},{"q":"¿Y financiacion / calculadora hipoteca?","a":"Calculadora hipoteca embebida + partner bancos con comision (UCI, Santander). Genera ingresos extra."}]'::jsonb,
 '/verticals/inmobiliaria.png',
 'Portal inmobiliaria con SEO y CRM integrado · PACAME · desde 3.999€',
 'Portal 500+ propiedades + CRM automation + app agentes + SEO local. Reduce dependencia Idealista. Entrega 28 dias.',
 true, 1),

('inmobiliaria', 'dueno-airbnb', 'Dueño / Gestor Airbnb',
 'Propietarios con 1-20 apartamentos Airbnb que quieren ingresos directos',
 '🔑',
 'Airbnb te cobra 14-20% y controla tu relacion con huespedes',
 '["14-20% comision = si facturas 80k/año Airbnb, pierdes 11-16k/año","Airbnb oculta emails huesped = no puedes fidelizar ni remarketear","Reseñas de Airbnb no te sirven fuera (otra plataforma = empezar de cero)","Competencia sube apartamentos iguales — tu solo compites por precio","Si Airbnb te suspende, pierdes 100% ingresos de la noche a la mañana"]'::jsonb,
 'Web directa + iCal sync + sistema reservas sin comision',
 '["Reserva directa con Stripe (1.4% vs 14-20% Airbnb)","iCal sync bidireccional Airbnb/Vrbo/Booking (cero bookings duplicados)","Tu marca + tu historia (apartamento con alma, no template Airbnb)","Email + WhatsApp automation pre-stay, check-in, post-stay","Programa fidelizacion: 2a estancia = 10% off directo + early check-in"]'::jsonb,
 '["Diseño premium tipo Airbnb pero TU marca","Motor reservas propio + Stripe + deposito + cleaning fee","iCal sync bidireccional con Airbnb + Vrbo + Booking","Multi-apartamento desde un panel (1-50 apartamentos)","Check-in digital automatico (DNI + codigo cerradura)","Email + WhatsApp automation 5 secuencias","Guide del barrio personalizada (PDF + web)","Multi-idioma ES/EN/FR + multi-moneda","Google Business + SEO local por barrio","Dashboard admin ocupacion + ADR + revenue"]'::jsonb,
 '{"client_name":"Sevilla Loft Collection (7 apts)","before":{"comision_Airbnb_año":"14.200€","reservas_directas_mes":3,"repetidores":"6%"},"after":{"comision_Airbnb_año":"5.400€","reservas_directas_mes":28,"repetidores":"31%"},"quote":"Pague 2.500€ una vez, ahorre 8.800€ en comisiones año 1. El 30% de huespedes vuelve porque los tengo en mi email.","disclaimer":"Simulacion basada en promedio propietario 5-10 apartamentos PACAME año 1"}'::jsonb,
 249900, 18,
 '[{"q":"¿Airbnb me suspende si tengo web propia?","a":"No. Prohibe enviar sus clientes fuera. Pero atraer clientes nuevos a tu web es legal. Es como tener Instagram ademas de Booking."},{"q":"¿Pierdo disponibilidad en Airbnb?","a":"No. iCal sync bidireccional. Reserva web = bloquea Airbnb automatico. Cero bookings duplicados."},{"q":"¿Stripe vs Airbnb cobro?","a":"Stripe 1.4% + 0.25€ vs Airbnb 14-20%. Si facturas 50k/año, ahorras 6-9k."},{"q":"¿Como evito fraudes reservas?","a":"Stripe Radar + deposito en caucion + DNI check-in digital. Igual o mejor que Airbnb."},{"q":"¿Multi-apartamento desde un panel?","a":"Si. 1-50 apartamentos con calendario, precio, fotos, guide independientes."},{"q":"¿Podemos vender extras (transfer, cesta, limpieza extra)?","a":"Si. Upsell checkout + email pre-stay. Margen 100% tuyo."},{"q":"¿SEO local por barrio?","a":"Si. Landing \"Apartamento Malasana\" + \"Apartamento Gracia\" con SEO local. Ranking Google orgánico."},{"q":"¿Y si el apartamento esta en Airbnb y quiero mandarlo a mi web?","a":"Tecnicamente prohibido por Airbnb TOS. Pero puedes atraer directo via Instagram, Google, referidos, tarjeta bienvenida con QR a tu web para la proxima estancia."}]'::jsonb,
 '/verticals/inmobiliaria.png',
 'Web directa apartamentos sin comision Airbnb · PACAME · desde 2.499€',
 'Ahorra 14-20% Airbnb. Reservas directas Stripe + iCal sync + programa fidelizacion. Entrega 18 dias.',
 true, 2),

('inmobiliaria', 'promotor', 'Promotor / Obra Nueva',
 'Promotoras inmobiliarias con desarrollos nuevos (edificios, urbanizaciones)',
 '🏗️',
 'Tu promocion de 80 viviendas vende a un ritmo de 2 al mes = necesitas 40 meses',
 '["Cliente decision compra 300k€+ = necesita 6-18 meses considerar","Sin landing promocion dedicada = compite con inmobiliarias portal","No tienes render 360 + fotos aereas + video dron = percepcion basica","Visita comercial = cliente pierde trabajo, mucha friccion","Sin calculadora hipoteca + simulacion compra no generas leads cualificados"]'::jsonb,
 'Landing promocion premium con render 360 + calculadora + tour virtual',
 '["Landing dedicada con gallery render 360 + video dron","Tour virtual navegable (tipologias A, B, C)","Calculadora: hipoteca + simulacion costes + compraventa","Reserva cita comercial (presencial + virtual videollamada)","Timeline obra + progreso fotos + garantias (aval, decenal)"]'::jsonb,
 '["Landing cinematografica con hero video aereo dron","Gallery render 360 por tipologia (A, B, C) navegable","Tour virtual interior navegable (Matterport)","Calculadora hipoteca + simulacion costes + compraventa (IVA, notaria, registro)","Pagina por tipologia con planos + fotos + precios + memoria calidades","Reserva visita comercial (presencial + video)","Timeline obra con progreso mensual (fotos + video)","Garantias legales visibles (aval bancario, decenal, seguro)","Integracion partner bancos (UCI, Santander) financing online","CRM leads calificados + scoring + agentes asignados"]'::jsonb,
 '{"client_name":"Promocion Costa Azul (La Habana Housing, 120 viviendas)","before":{"ventas_mes":2,"leads_web_mes":18,"visitas_comerciales":"4 al mes"},"after":{"ventas_mes":6,"leads_web_mes":94,"visitas_comerciales":"22 al mes"},"quote":"El tour virtual 24/7 triplico las leads cualificadas. La calculadora financing convierte visitantes frios en citas calientes. Pasamos de vender 2 al mes a 6.","disclaimer":"Simulacion basada en promedio promocion 60-150 viviendas PACAME primer año"}'::jsonb,
 599900, 35,
 '[{"q":"¿Render 360 y tour virtual los hacemos nosotros?","a":"Tu contratas el servicio 3D/Matterport (150-800€ c/u segun calidad). Nosotros integramos en la web."},{"q":"¿Financing con bancos como?","a":"Partner con UCI (Santander) + ActivoBank + otros. Cliente simula hipoteca en tu web, si califica, banco contacta = lead cualificado."},{"q":"¿Multi-promocion?","a":"Si. 1-20 promociones desde panel unico. Cada una con landing independiente + CRM agrupado."},{"q":"¿CRM agentes vs Salesforce?","a":"Propio suficiente para promotora <500 viviendas/año. Salesforce integracion 2-3 semanas extra si la necesitas."},{"q":"¿Reserva online con deposito?","a":"Si. Stripe autorizaciones (retiene sin cobrar) o cobro parcial (1.000-5.000€ reserva) que se aplica al contrato."},{"q":"¿Timeline obra automatizado?","a":"Panel admin sube foto + descripcion mes. Publica automatico en pagina cliente. Email a reservistas con progreso."},{"q":"¿Mejor que Idealista / Fotocasa?","a":"Complementario. Promocion obra nueva en Idealista = aparece como 80 anuncios repetidos. Landing propia con tour virtual = vende una marca."},{"q":"¿Y para second home / inversores extranjeros?","a":"Multi-idioma ES/EN/FR/DE + geo-pricing + financing specific para no-residentes incluido."}]'::jsonb,
 '/verticals/inmobiliaria.png',
 'Landing promocion obra nueva con tour virtual · PACAME · desde 5.999€',
 'Render 360 + tour virtual + calculadora financing + CRM agentes. Triplica leads cualificados. Entrega 35 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: ECOMMERCE
-- ══════════════════════════════════════════════════════════════════════════
('ecommerce', 'tienda-online', 'Tienda Online DTC',
 'Marcas direct-to-consumer con catalogo propio (ropa, cosmetica, food)',
 '🛍️',
 'Shopify te cobra 29-299€/mes + transaction fee y Amazon se lleva 15%',
 '["Shopify Basic 29€ + transaction 2% = escalas y te comen margen","Amazon vende = cede 15% + tus clientes = Amazon los fideliza, no tu","Sin programa referidos pierdes el 30% repeat purchase potencial","Tu blog Shopify es limitado (SEO generico template)","App mobile nativa es 10k+ en Shopify App Store"]'::jsonb,
 'E-commerce propietario Next.js + Stripe directo + PWA mobile',
 '["Stack propio Next.js + Stripe (sin transaction fees extra)","PWA mobile instalable como app nativa sin App Store","Programa referidos: cliente da codigo, ambos ganan","SEO ilimitado (blog personalizado, product SEO, schema markup)","Automation email: carrito abandonado, repurchase, VIP segment"]'::jsonb,
 '["Diseño premium DTC + fotos producto HD","Catalogo ilimitado con Stripe checkout","PWA mobile instalable (iOS + Android, cero App Store)","Programa referidos + codigos descuento","Email automation: bienvenida, abandono carrito, repurchase, post-compra","Blog SEO ilimitado con 10 posts iniciales","Integracion envios (Correos, Seur, Colissimo) + tracking","Reviews producto + fotos user-generated","Multi-idioma ES/EN + multi-moneda","Dashboard: LTV, CAC, cohorts, cart abandonment rate"]'::jsonb,
 '{"client_name":"Marca Cosmetica Natural (45k€/mes)","before":{"shopify_cost_mes":"299€ + 1.350€ fees","abandono_carrito":"72%","LTV":"48€"},"after":{"pacame_cost_mes":"hosting 29€","abandono_carrito":"54%","LTV":"87€"},"quote":"Ahorramos 1.600€/mes solo en Shopify fees. La PWA mejoro retencion mobile +40%. El LTV casi se duplico con automation email.","disclaimer":"Simulacion basada en promedio ecommerce DTC PACAME año 1"}'::jsonb,
 299900, 21,
 '[{"q":"¿Migracion desde Shopify es dificil?","a":"Tomamos tu catalogo (CSV export), clientes, pedidos historicos, reviews. Sin perder SEO (redirects). Go-live en staging primero."},{"q":"¿PWA vs App Store real?","a":"PWA se instala desde Safari/Chrome con 1 tap. Usuario experiencia igual app. Ahorra 99€/año Apple + gestion version."},{"q":"¿Reviews vs Shopify App?","a":"Reviews producto + fotos UGC propio (sin app fee). Integracion Yotpo/Stamped si ya las usas."},{"q":"¿Shipping labels integracion?","a":"Si. Correos, Seur, Colissimo, SEUR directo. Automatico crea label al confirmar pedido."},{"q":"¿Stripe Europa vs Shopify Payments?","a":"Stripe 1.4% + 0.25€ (igual). Pero Stripe te da + flexibilidad, Apple Pay, Google Pay, Klarna, direct SEPA."},{"q":"¿Automation email vs Klaviyo?","a":"Resend + templates propios (80% casos basta). Klaviyo integracion extra si ya lo usas."},{"q":"¿Multi-idioma y multi-moneda?","a":"Si. ES/EN/FR + EUR/USD/GBP nativo. Tax automatico (VAT inversion, RF)."},{"q":"¿Dashboard LTV/CAC real?","a":"Si. Cohorts por mes, LTV 30/90/365, CAC por canal, ROAS. Data visualizada D3."}]'::jsonb,
 '/verticals/ecommerce.png',
 'Ecommerce propietario DTC · PACAME · desde 2.999€',
 'Stripe directo + PWA mobile + programa referidos + email automation. Sin fees Shopify. Entrega 21 dias.',
 true, 1),

('ecommerce', 'dropshipping', 'Dropshipping / Reseller',
 'Tiendas online sin stock propio (dropshipping, print-on-demand, reseller)',
 '📦',
 'Tu Shopify de dropshipping genera 3-5k/mes pero Facebook Ads se come 60% margen',
 '["CPM Facebook Ads sube mensualmente, hoy paga 15-30€ por conversion","Tu tienda luce generica (tema Shopify + AliExpress import) = no recurrencia","Sin email marketing fuerte, dependes 100% ads = fragil si Facebook te banea","Shopify Basic + transaction fees + app fees = 200-400€/mes","No escalas porque cada nuevo SKU tarda 1 semana de configurar"]'::jsonb,
 'Stack propio con import masivo + SEO + funnel ventas',
 '["Import masivo CSV proveedor (AliExpress, DSers, Spocket) + markup rules","Tienda con tu MARCA (no generic Shopify theme)","SEO ranker (productos long-tail) = traffic organic reduce dependencia Ads","Email marketing core: abandono, post-compra, repurchase, flash sale","Analytics margen real por producto + canal (FB vs Google vs Email)"]'::jsonb,
 '["Diseño custom branded (no Shopify generic)","Import masivo CSV + API partners dropshipping","Stripe checkout con upsell + cross-sell","SEO programatico (300 producto pages ranker Google)","Email marketing automation (Resend templates pro)","Integracion analytics: margen real por SKU, canal, campaña","Multi-currency + multi-idioma","Retail arbitrage dashboard: margen minimo alert","Integracion Meta Pixel + Google Ads + TikTok Pixel","A/B testing nativo (home, product, checkout)"]'::jsonb,
 '{"client_name":"Dropship Home Decor Store","before":{"margen_neto":"18%","dependencia_FB_ads":"85%","LTV":"42€"},"after":{"margen_neto":"34%","dependencia_FB_ads":"52%","LTV":"78€"},"quote":"El SEO organico nos dio 30% trafico gratis. El email marketing triplico LTV. Pasamos de 18% a 34% margen neto. Inversion pagada en 4 meses.","disclaimer":"Simulacion basada en promedio tienda dropshipping PACAME primer año"}'::jsonb,
 189900, 16,
 '[{"q":"¿Import desde AliExpress como?","a":"Conectores con DSers, Spocket, Zendrop. Filtra productos + markup automatico + sync stock bidireccional."},{"q":"¿SEO programatico 300 pages?","a":"Si. Template producto con long-tail (\"[producto] [marca] [color]\") genera paginas unicas optimizadas SEO."},{"q":"¿Facebook Ads vs email?","a":"FB siempre subira costes. Email es CHEAP: 100 envios/dia = 10€/mes. Convierte 4x mejor que FB para repurchase."},{"q":"¿Migracion Shopify preserva SEO?","a":"Si. 301 redirects + sitemap + schema markup migration. Sin perder ranking Google."},{"q":"¿Dashboard margen real?","a":"Si. Coste producto + coste envio + fee Stripe + impuesto + ads CPA = margen neto real por SKU."},{"q":"¿Multi-pais vende directamente?","a":"Si. Stripe + shipping rules por zona + tax auto (EU VAT, US sales tax)."},{"q":"¿A/B testing nativo?","a":"Si. Testea hero copy, product pricing, upsell, checkout flow. Reporta conversiones por variant."},{"q":"¿Escalable a 1000+ SKUs?","a":"Si. CDN Vercel + Supabase handle millones products. Sin limite practico."}]'::jsonb,
 '/verticals/ecommerce.png',
 'Ecommerce dropshipping con SEO organico · PACAME · desde 1.899€',
 'Import masivo + SEO programatico + email marketing. Reduce dependencia Facebook Ads 40%. Entrega 16 dias.',
 true, 2),

('ecommerce', 'marketplace-seller', 'Vendedor Marketplace',
 'Vendedores en Amazon, Etsy, eBay, Vinted que quieren sacar marca propia',
 '🏪',
 'Amazon te da trafico pero tu marca es invisible y compites con clones chinos',
 '["Amazon vende = cede 15% + no sabes quien es tu cliente","Clones chinos te copian con mismo producto en 2 meses","Sin marca propia fuerte, eres commodity reemplazable","Amazon controla pricing (Buy Box) y banning es arbitrario","No puedes hacer email marketing ni retargeting a tus clientes Amazon"]'::jsonb,
 'Sitio DTC paralelo que convierte fans de Amazon en marca propia',
 '["Web propia con tu marca + historia = diferencial vs clones","Inserto en paquete Amazon: \"Visita nuestro sitio para 20% off\"","Email + SMS marketing a clientes web (no Amazon)","Programa VIP / suscripcion auto-ship","SEO propio que no depende Amazon"]'::jsonb,
 '["Diseño marca premium propia DTC","Stripe checkout + multi-tier pricing","Inserto paquete Amazon con QR code (converter Amazon to DTC)","Email marketing automation + SMS","Programa VIP con subscription auto-ship","SEO propio con producto pages + blog","Integracion fulfilment (FBA-export, Colissimo, Correos)","Reviews autenticas + fotos UGC","Multi-idioma + multi-moneda","Dashboard: % Amazon vs DTC sales + LTV comparativa"]'::jsonb,
 '{"client_name":"Marca Accesorios Tech (ex-Amazon seller)","before":{"pct_Amazon_ventas":"100%","LTV":"32€","DTC_web":"0€/mes"},"after":{"pct_Amazon_ventas":"58%","LTV":"76€","DTC_web":"8.400€/mes"},"quote":"El inserto QR en el paquete Amazon convirtio 8% de clientes Amazon a DTC en 6 meses. Cada euro DTC vale 3x un euro Amazon (sin fee + mejor LTV).","disclaimer":"Simulacion basada en promedio seller Amazon PACAME primeros 180 dias"}'::jsonb,
 159900, 14,
 '[{"q":"¿Amazon banea por mandar clientes a mi web?","a":"No tecnicamente. Prohibe usar datos Amazon (email cliente) para ellos. Pero inserto paquete es 100% legal: tu empaquetas, tu decides que meter."},{"q":"¿Inserto en paquete vale la pena?","a":"Si. Conversion rate tipico: 5-10% clientes que hacen segunda compra DTC. LTV 3x Amazon (no 15% fee + repeat)."},{"q":"¿Cross-platform Etsy/eBay/Amazon?","a":"Si. Sync inventario con cada marketplace (ChannelAdvisor integration o manual sync)."},{"q":"¿Email con datos que tengo?","a":"No los de Amazon (violas TOS). Si los de tu web (cliente que completa checkout DTC)."},{"q":"¿Programa VIP real convierte?","a":"Si. Auto-ship mensual (suscripcion) reduce churn 45%. Descuento 15% vs compra unica = cliente decide una vez."},{"q":"¿Fulfilment opciones?","a":"FBA (Amazon hace envio tu web), Correos propio, Colissimo, Seur. Te asesoramos segun volumen."},{"q":"¿SEO propio vs Amazon SEO?","a":"Complementario. Amazon SEO dentro Amazon, Google SEO en tu web. No compiten."},{"q":"¿Reviews reales sin Amazon?","a":"Si. Email post-compra request review + fotos. Incentivo pequeño (5% off proxima). Legal."}]'::jsonb,
 '/verticals/ecommerce.png',
 'Web DTC para vendedor marketplace · PACAME · desde 1.599€',
 'Convierte clientes Amazon en marca propia. Inserto paquete + email marketing + programa VIP. Entrega 14 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: FORMACION
-- ══════════════════════════════════════════════════════════════════════════
('formacion', 'academia', 'Academia / Escuela',
 'Academias de idiomas, oposiciones, formacion profesional (50-500 alumnos)',
 '🎓',
 'Tu academia llena aulas por boca a boca pero Google no te encuentra',
 '["Google \"academia ingles [ciudad]\" no sales top 5 = pierdes 70% busquedas","Inscripcion es formulario -> llamada -> email -> reserva = 4 pasos = abandono","Sin demo clases no puedes mostrar calidad de profesorado","Competencia Wall Street / Kaplan tiene branding nacional + SEO","Pago matricula efectivo/transferencia = friccion + no subscripciones"]'::jsonb,
 'Web moderna con demo clases + matriculacion online + SEO local',
 '["Matricula online con Stripe + pago fraccionado","Demo clase gratis (video o en vivo) = conversion x3","SEO local dominante (\"academia [idioma] [ciudad]\")","Sistema testimonios video alumnos + resultados","Portal alumno con material + calendario + progreso"]'::jsonb,
 '["Diseño academico + confianza","Matricula online Stripe (pago completo o fraccionado 3/6 meses)","Demo clase: video grabado o reserva clase en vivo","Pagina por curso con programa + profesorado + resultados","SEO local dominante + blog metodologico","Portal alumno con material + calendario + progreso","Testimonios video alumnos + antes/despues (niveles idioma, notas oposicion)","Reviews Google + Trustpilot agregadas","Integracion Zoom/Whereby para clases online","Multi-idioma ES/EN/CA (segun audiencia academia)"]'::jsonb,
 '{"client_name":"Academia English Plus (Valencia)","before":{"matriculas_online":0,"web_conversion":"1.4%","nuevos_alumnos_mes":14},"after":{"matriculas_online":"38 al mes","web_conversion":"5.2%","nuevos_alumnos_mes":47},"quote":"Pasamos de llamadas a matricula 100% online. La demo clase en vivo convierte 3x mejor que PDF informativo. Los sabados ya no trabajamos.","disclaimer":"Simulacion basada en promedio academia PACAME primer año"}'::jsonb,
 179900, 16,
 '[{"q":"¿Pago fraccionado legal?","a":"Si. Stripe maneja planes mensuales. Si cliente falla pago 2 meses seguidos, bloquea acceso automatico."},{"q":"¿Demo clase en vivo vs video?","a":"Ambas. Video para conversion rapida (link inmediato). Live class para cualificar leads calientes (semanal)."},{"q":"¿Portal alumno con material?","a":"Si. PDF, video, audio organizados por curso/nivel. Alumno accede 24/7 con login."},{"q":"¿Multi-profesor + comisiones?","a":"Si. Cada profesor su calendario + horas impartidas + sistema comisiones automaticas."},{"q":"¿Integra con Moodle o plataformas existentes?","a":"Si. Moodle, Google Classroom, Canvas. Sync calificaciones + asistencia."},{"q":"¿Reviews Trustpilot real?","a":"Widget Trustpilot + Google reviews agregados. Aumenta trust + SEO."},{"q":"¿SEO local cuanto tarda?","a":"Top 10: 2-3 meses. Top 3: 4-6 meses. Con blog metodologico + backlinks locales."},{"q":"¿B2B corporate training?","a":"Si. Pagina dedicada empresas + formulario cotizacion grupo + facturacion B2B."}]'::jsonb,
 '/verticals/formacion.png',
 'Web para academia con matricula online y SEO · PACAME · desde 1.799€',
 'Matricula Stripe + demo clase + SEO local + portal alumno. Llena aulas automatico. Entrega 16 dias.',
 true, 1),

('formacion', 'coach-solo', 'Coach Individual / Mentor',
 'Coaches individuales (vida, business, salud mental, fitness)',
 '🧑‍🏫',
 'Vendes sesiones 1-on-1 y tu ingreso depende de las horas que puedas trabajar',
 '["50 sesiones/mes a 80€ = 4.000€/mes = techo duro","Tus clientes son de Instagram DM = convierten solo 3-5%","No tienes programa online escalable ni comunidad pagada","Sin email list pierdes relacion una vez termina sesion","Competidores con 10k seguidores venden cursos online 10x mas"]'::jsonb,
 'Web funnel + programa online + comunidad mensual escalable',
 '["Sesiones 1-on-1 con pricing premium + tiers","Programa online 8-12 semanas (199-499€) vendible infinito","Comunidad privada mensual (49€/mes × 100 miembros = 4.900€/mes pasivos)","Email list + funnel: lead magnet -> nurture -> venta","Certificado digital al completar programa (LinkedIn shareable)"]'::jsonb,
 '["Landing personal storytelling (tu historia, resultados, filosofia)","Sistema sesiones 1-on-1 Stripe + calendario","Venta programa online con lecciones en video","Comunidad privada foro + calls mensuales","Email funnel: lead magnet (PDF gratis) -> nurture -> venta","Biblioteca recursos (audios guia, ebooks, worksheets)","Certificado digital (LinkedIn shareable)","Integracion Instagram / YouTube / TikTok","Faturacion automatica Stripe + Facturae","Analytics ingresos por canal + programa + cliente"]'::jsonb,
 '{"client_name":"Coach Mindset (ex-corporate)","before":{"ingresos_mes":"3.200€","clientes_activos":12,"programa_online":0},"after":{"ingresos_mes":"11.400€","sesiones_1on1":"20/mes","programa_vendido":"87 totales","comunidad_miembros":64},"quote":"Mi programa de 8 semanas a 349€ se vende en automatico. Mi comunidad de 49€/mes genera 3.100€ pasivos. Ingresos x3.5 sin trabajar mas horas.","disclaimer":"Simulacion basada en promedio coach individual PACAME primer año"}'::jsonb,
 119900, 12,
 '[{"q":"¿Programa online vende solo despues de grabar?","a":"Si. Grabas 8-12 videos (2-3h trabajo), subes. Vende 100+ veces sin trabajo extra. Automation email onboarding."},{"q":"¿Comunidad privada vs Discord?","a":"Discord gratis = 0% conversion. Plataforma con pago = barrera entrada = compromiso. Miembros pagan = participan."},{"q":"¿Calls mensuales Zoom incluido?","a":"Si. Integracion Zoom + calendario. Miembros reciben link directo."},{"q":"¿Certificado LinkedIn shareable?","a":"Si. PDF + posteable en LinkedIn con tu marca. Efecto viral: cada cert = visibilidad tu marca."},{"q":"¿Stripe recurrentes para comunidad?","a":"Si. Mensual/anual. Cliente puede pausar/cancelar desde su perfil."},{"q":"¿Funnel email herramientas?","a":"Resend (simple + cheap) o ConvertKit integracion si ya lo usas."},{"q":"¿Programa multi-nivel?","a":"Si. Modulo 1 gratuito (hook) -> Modulo 2 paid -> Modulo avanzado premium. Upsell automatico."},{"q":"¿Grabacion videos calidad?","a":"Basic: iPhone + microfono 30€ basta para empezar. Upgrade despues si quieres (Loom, Riverside, camara DSLR)."}]'::jsonb,
 '/verticals/formacion.png',
 'Web + programa online para coach · PACAME · desde 1.199€',
 'Sesiones 1-on-1 + programa online escalable + comunidad mensual. Escala ingresos sin horas. Entrega 12 dias.',
 true, 2),

('formacion', 'universidad', 'Universidad / Business School',
 'Universidades privadas y business schools con programas masters/MBA',
 '🎓',
 'Tu universidad compite con IE / ESADE / IESE por alumnos que pagan 30k+/año',
 '["Alumno MBA compara tu programa vs IE/ESADE/IESE en 4-6 meses","Sin landing programa especifica con testimonios alumni + ranking rigor","Proceso admision = formularios + tests + entrevistas = alta friccion","No muestras salidas profesionales + placement stats = basic selling","Sin comunidad alumni activa pierdes network value propuesta"]'::jsonb,
 'Landing programas premium + placement data + alumni portal',
 '["Landing programa con ROI data + placement stats reales","Alumni portal con directorio + newsletter + eventos","Entrevista virtual 15 min como primer screening","Webinars recurrentes con profesorado estrella","Sistema tests admision online (GMAT-like) integrado"]'::jsonb,
 '["Landing programa con ROI + placement data + testimonios video","Sistema admision online: formulario + CV + test + entrevista","Alumni portal: directorio, newsletter, eventos, ofertas laborales","Webinars recurrentes profesorado + recording library","Catalogo programas: master, MBA, executive, doctorado","Pagina profesorado con papers + linkedin + videos","Integracion CRM enrollment (Salesforce/HubSpot)","Multi-idioma ES/EN (internacionalizacion)","Analytics embudo: visita -> interes -> aplicacion -> admitido -> enrolled","Chat en vivo + scheduler citas virtuales"]'::jsonb,
 '{"client_name":"Business School Regional","before":{"solicitudes_MBA":"45/año","conversion_aplicacion_enrollment":"18%","budget_paid_ads":"120k€/año"},"after":{"solicitudes_MBA":"168/año","conversion_aplicacion_enrollment":"32%","budget_paid_ads":"80k€/año (reinversion SEO)"},"quote":"Triplicamos aplicaciones MBA. El alumni portal creo efecto network que vendio solo. El SEO organico nos libero 40k€ anual de paid ads.","disclaimer":"Simulacion basada en promedio business school PACAME primer año"}'::jsonb,
 599900, 42,
 '[{"q":"¿Integra con Salesforce Higher Ed?","a":"Si. Integracion completa: lead capture, scoring, nurturing, enrollment. Sync bidireccional."},{"q":"¿Tests admision online legal?","a":"Si. Con proctoring (screen + camara) validamos identidad. Cumple AACSB y EFMD standards."},{"q":"¿Multi-programa desde panel?","a":"Si. Master, MBA, Executive, Doctorado con paginas dedicadas, funnels distintos, lead scoring diferenciado."},{"q":"¿Alumni portal con directorio?","a":"Si. Directorio searchable por sector/empresa/pais + mensajeria interna + eventos."},{"q":"¿Webinars recording library?","a":"Si. Post-evento recording disponible para aplicantes (lead magnet) + alumni (community)."},{"q":"¿Ranking / acreditacion display?","a":"Si. Badges AACSB, EQUIS, AMBA si aplica + Financial Times ranking + otros."},{"q":"¿Multi-idioma completo?","a":"Si. ES/EN completo. Traduccion profesional copywriter higher-education specific. Expansion PT/DE opcional."},{"q":"¿Paid ads integration?","a":"Si. Google Ads + LinkedIn Campaign Manager + Meta Ads. Atribucion multi-touch para attribution conversion."}]'::jsonb,
 '/verticals/formacion.png',
 'Web para universidad o business school · PACAME · desde 5.999€',
 'Landing programa + admision online + alumni portal + placement data. Triplica solicitudes MBA. Entrega 42 dias.',
 true, 3),

-- ══════════════════════════════════════════════════════════════════════════
-- VERTICAL: SAAS
-- ══════════════════════════════════════════════════════════════════════════
('saas', 'early-stage', 'SaaS Early-Stage (Pre-Series A)',
 'SaaS startups 0-1M ARR, buscando product-market fit',
 '🚀',
 'Tu SaaS funciona tecnicamente pero tu landing convierte 0.8% y no sabes por que',
 '["Tu landing es dev-focused (features + tech stack) = no vende beneficio","Conversion 0.8% vs industria top 3-5% = fugas multi-etapa","Sin comparacion competidor ni social proof = duda compra","Onboarding es \"crea cuenta + explora\" = 70% churn primera semana","Sin SEO programatico long-tail pierdes 90% busquedas intencionales"]'::jsonb,
 'Landing B2B + comparador + onboarding + SEO programatico',
 '["Landing B2B tier Stripe/Linear con social proof visible","Comparador competidor (tu vs [competitor]) = acelera decision","Onboarding personalizado segun persona (founder / CTO / Ops)","SEO programatico: 500 pages long-tail use-case","Documentation + changelog publico = senial producto vivo"]'::jsonb,
 '["Diseño B2B SaaS tier-1 (Linear/Stripe inspired)","Landing con hero video producto + feature tour","Comparador competidor paralelo (tu vs Intercom/Zendesk/etc)","Onboarding personalizado por rol + industria","SEO programatico: 500+ pages long-tail generadas","Pricing interactivo + calculator ROI","Integraciones display (logos clientes + tools compatibles)","Documentation publica + changelog + roadmap","Blog SEO con 15 posts iniciales","Analytics embudo: visit -> signup -> activation -> paid"]'::jsonb,
 '{"client_name":"SaaS B2B (pre-Series A, 380k ARR)","before":{"conversion_web":"0.9%","signups_mes":"42","churn_mes_1":"68%"},"after":{"conversion_web":"3.8%","signups_mes":"187","churn_mes_1":"41%"},"quote":"La landing tier Stripe convirtio 4x mejor. El comparador vs Intercom dobla deals enterprise. El SEO programatico nos da 40% signups organicos.","disclaimer":"Simulacion basada en promedio SaaS pre-Series A PACAME primer año"}'::jsonb,
 299900, 24,
 '[{"q":"¿Comparador competidor legal?","a":"Si, con data objetiva verificada. Evita afirmaciones falsas (\"somos mejores\") y usa features especificas (\"soportamos X, ellos no\")."},{"q":"¿SEO programatico 500 pages?","a":"Si. Template use-case con combinatoria (persona × industria × feature). Genera pages unicas optimizadas long-tail."},{"q":"¿Onboarding personalizado por rol?","a":"Si. Cliente responde 2-3 preguntas en signup (rol, tamaño, uso principal). Recibe onboarding + emails + dashboard adaptados."},{"q":"¿Documentation publica necesaria?","a":"Si para B2B. Docusaurus/Mintlify + search. Reduce tickets soporte -40% y acelera evaluation deals."},{"q":"¿Pricing interactivo?","a":"Si. Slider por numero usuarios/seats/calls = ve precio adapta en tiempo real. Reduce friccion enterprise."},{"q":"¿Integracion ProductHunt / G2?","a":"Si. Embed reviews G2/Capterra + ProductHunt badge + social proof dinamico."},{"q":"¿Changelog publico vale?","a":"Si. Producto vivo + transparent + build in public. Convierte 15% mas enterprise deals vs sin changelog."},{"q":"¿Multi-idioma Series A?","a":"ES/EN minimo. FR/DE cuando expansion europea. Traduccion copywriter SaaS specific."}]'::jsonb,
 '/verticals/saas.png',
 'Web para SaaS early-stage · PACAME · desde 2.999€',
 'Landing tier-1 + comparador + onboarding + SEO programatico. Convierte 4x vs baseline. Entrega 24 dias.',
 true, 1),

('saas', 'scaleup', 'SaaS Scale-up (Series A-B)',
 'SaaS 1-10M ARR, escalando enterprise + rebranding visual',
 '📈',
 'Tu SaaS pasa de SMB a Enterprise pero tu web sigue pareciendo startup',
 '["Deals enterprise 50k+ requieren website tier-1 + security page + customer stories","Tu website actual luce startup: amateur vs competidores enterprise","Sin trust badges (SOC2, ISO27001, GDPR detailed) pierdes deals Fortune 500","Sin case studies detallados por vertical, prospects eligen mas establecidos","Onboarding generico = churn alto entre enterprise-trial"]'::jsonb,
 'Website enterprise-grade + security page + customer stories + partner portal',
 '["Rebrand visual tier Linear/Databricks (no mas startup-y)","Security page con SOC2 + ISO + GDPR + penetration tests","Customer stories detalladas con metricas financieras reales","Partner portal (resellers, integrators, consultants)","Onboarding enterprise custom por vertical (FinServ, Health, Retail)"]'::jsonb,
 '["Rebrand visual enterprise-grade tier-1","Security & compliance page completa (SOC2, ISO27001, GDPR detalles)","Customer stories (10+ cases por vertical con metricas)","Partner portal publico + aplicacion + tracking","Pricing enterprise con \"Contact sales\" + calendar scheduler","Onboarding custom por vertical","Resource center: whitepapers, reports, webinars","Blog B2B con guest authors + SEO estrategia","Integraciones display + partner program","Multi-idioma ES/EN/FR/DE + multi-region compliance"]'::jsonb,
 '{"client_name":"SaaS B2B (Serie A, 3.2M ARR)","before":{"deals_enterprise_mes":4,"ACV_promedio":"18k€","ciclo_venta":"4.5 meses"},"after":{"deals_enterprise_mes":11,"ACV_promedio":"34k€","ciclo_venta":"2.8 meses"},"quote":"La website enterprise + security page + customer stories cerraron 3x mas deals enterprise. ACV subio 88%. Cicle venta bajo de 4.5 a 2.8 meses.","disclaimer":"Simulacion basada en promedio SaaS Serie A PACAME primer año"}'::jsonb,
 499900, 35,
 '[{"q":"¿Security page real con SOC2?","a":"Si. Si tienes SOC2/ISO certificates, los mostramos + detalles. Si estas en proceso, indicamos roadmap compliance."},{"q":"¿Customer stories data real?","a":"Con consent cliente. Firma release + nos da acceso metricas (CEO approval). Inflacion prohibida."},{"q":"¿Partner portal?","a":"Si. Aplicacion publica + review interna + onboarding partner + tracking deals + comisiones."},{"q":"¿Rebrand visual completo?","a":"Si. Logo nuevo opcional + guidelines + templates + website + email signatures + decks ventas."},{"q":"¿Enterprise pricing \"Contact Sales\"?","a":"Si. Modal con calendar scheduler + lead scoring automatic + alerta sales."},{"q":"¿Resource center con whitepapers?","a":"Si. 5-10 reports iniciales + gated (email) + drip automation."},{"q":"¿Multi-region compliance?","a":"GDPR (EU), CCPA (California), LGPD (Brasil). Cookie consent adaptable por geo."},{"q":"¿Blog estrategia SEO topic clusters?","a":"Si. 10 pilar pages + 50 cluster articles = authority topic especifico. Organic traffic 6-12 meses."}]'::jsonb,
 '/verticals/saas.png',
 'Web enterprise para SaaS Series A-B · PACAME · desde 4.999€',
 'Rebrand tier-1 + security page + customer stories + partner portal. Cierra 3x deals enterprise. Entrega 35 dias.',
 true, 2),

('saas', 'enterprise', 'SaaS Enterprise (Series C+)',
 'SaaS 10M+ ARR, expansion internacional + multi-producto',
 '🏛️',
 'Tu SaaS vende Fortune 500 pero tu web no se diferencia de Salesforce/Oracle',
 '["Web actual es coleccion features, no habla negocio","Cada producto (Platform + AI Add-on + Industry Module) compite por atencion","Sin Analyst Reports (Gartner, Forrester) ni featured = pierdes credibilidad tier-1","RFP requirements no documentados en web = sales lose 2 weeks por request","Internationalization incompleta = pierdes regional expansion"]'::jsonb,
 'Website multi-producto + analyst relations + RFP center + international sites',
 '["Architecture multi-producto con navegacion por industria + rol + region","Analyst page (Gartner, Forrester, IDC featured)","RFP/Security center documentation completa","International sites (US, EU, APAC) con contenido localizado","Partner ecosystem portal + marketplace apps"]'::jsonb,
 '["Multi-producto architecture (platform + add-ons + modules)","Analyst relations page (Gartner MQ, Forrester Wave, IDC MarketScape)","RFP center: security, compliance, legal, integration docs descargables","International sites multi-region (US, EU, APAC)","Partner ecosystem publico + marketplace aplicaciones","Customer success stories filtrables por vertical/region/size","Customer advocacy portal + referenciable logos","Investor relations page si publico","Brand architecture multi-product coherente","Integracion Salesforce/HubSpot enterprise stack"]'::jsonb,
 '{"client_name":"SaaS Enterprise (Series C, 28M ARR)","before":{"deals_F500":"3 al año","RFP_win_rate":"22%","time_to_RFP":"2 semanas"},"after":{"deals_F500":"9 al año","RFP_win_rate":"41%","time_to_RFP":"2 dias (self-service)"},"quote":"RFP center self-service redujo time-to-RFP de 2 semanas a 2 dias. Analyst page cerro 2 deals Gartner-peer-recommend. 3x deals F500.","disclaimer":"Simulacion basada en promedio SaaS Series C PACAME primer año"}'::jsonb,
 999900, 56,
 '[{"q":"¿RFP center documentos confidenciales?","a":"No. Docs publicos (security overview, compliance certs, integration docs). Enterprise-specific details via NDA gated download."},{"q":"¿Analyst relations page con datos reales?","a":"Si, con permiso Gartner/Forrester para mostrar badges + quotes exactos (reporte pagado libre referencia publica)."},{"q":"¿Multi-region site expansion?","a":"Si. US (pacame.com/us), EU (pacame.com/eu), APAC (pacame.com/apac). Contenido + compliance + pricing adaptados."},{"q":"¿Partner ecosystem con marketplace?","a":"Si. Marketplace apps third-party + featured partners + integracion install 1-click."},{"q":"¿Investor relations si cotizamos?","a":"Si. IR site separado con SEC filings, earnings calls, press releases."},{"q":"¿Multi-producto navigation sin confundir?","a":"Architecture jerarquica: Platform core + Add-ons + Industry Modules. Mega menu con icono + tagline each."},{"q":"¿Customer advocacy con referenciables?","a":"Si. Portal alumni pago (speak at events, beta testers, references) con tracking engagement."},{"q":"¿Integra con nuestro Salesforce enterprise?","a":"Si. Salesforce Sales Cloud, Service Cloud, Marketing Cloud full integration. Lead scoring + routing + nurturing automatic."}]'::jsonb,
 '/verticals/saas.png',
 'Web enterprise SaaS Series C+ · PACAME · desde 9.999€',
 'Multi-producto + analyst relations + RFP center + international sites. Cierra Fortune 500. Entrega 56 dias.',
 true, 3)

ON CONFLICT (vertical_slug, persona_slug) DO UPDATE SET
  persona_name = EXCLUDED.persona_name,
  persona_tagline = EXCLUDED.persona_tagline,
  persona_emoji = EXCLUDED.persona_emoji,
  pain_headline = EXCLUDED.pain_headline,
  pain_bullets = EXCLUDED.pain_bullets,
  solution_headline = EXCLUDED.solution_headline,
  solution_bullets = EXCLUDED.solution_bullets,
  deliverables = EXCLUDED.deliverables,
  case_study = EXCLUDED.case_study,
  starting_price_cents = EXCLUDED.starting_price_cents,
  timeline_days = EXCLUDED.timeline_days,
  faq = EXCLUDED.faq,
  hero_image_url = EXCLUDED.hero_image_url,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
